const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const FETCH_STREAMS = "FETCH_STREAMS";
const FETCH_STREAM = "FETCH_STREAM";
const CREATE_STREAM = "CREATE_STREAM";
const EDIT_STREAM = "EDIT_STREAM";
const DELETE_STREAM = "DELETE_STREAM";

export {
  SIGN_IN,
  SIGN_OUT,
  FETCH_STREAMS,
  FETCH_STREAM,
  CREATE_STREAM,
  EDIT_STREAM,
  DELETE_STREAM,
};
